//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasarim3B.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tasarim3B.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Tasarım3B - Dolap Tasarım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataGrid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DataGridPageTitle {
            get {
                return ResourceManager.GetString("DataGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlemler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RibbonTab1Baslik {
            get {
                return ResourceManager.GetString("RibbonTab1Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RibbonTabGrup1 {
            get {
                return ResourceManager.GetString("RibbonTabGrup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firma benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RibbonTabGrup2 {
            get {
                return ResourceManager.GetString("RibbonTabGrup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Levhalar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RibbonTabGrup3 {
            get {
                return ResourceManager.GetString("RibbonTabGrup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings page placeholder text.  Your app description goes here. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About this application benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Theme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personalization benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy Statement benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ShellPageRibbonBackstageTabSettingsHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonBackstageTabSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çizim İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ShellPageRibbonHomeGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeGroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common Group 2 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ShellPageRibbonHomeGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeGroupCommon2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ShellPageRibbonTabHomeHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabHomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Açık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TabGroupTemaAcik {
            get {
                return ResourceManager.GetString("TabGroupTemaAcik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Koyu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TabGroupTemaKoyu {
            get {
                return ResourceManager.GetString("TabGroupTemaKoyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tema benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TabGrupTema {
            get {
                return ResourceManager.GetString("TabGrupTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Göster/Gizle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TabYanPencereGoster {
            get {
                return ResourceManager.GetString("TabYanPencereGoster", resourceCulture);
            }
        }
    }
}
